# Profil de l'utilisateur pour personnaliser Jarvis
nom: "Jérémie"
mode: "focus"
objectifs:
  - "Construire une IA personnelle complète"
  - "Automatiser mes routines"
  - "Avancer sur mes projets tech"
style:
  langage: "naturel, direct"
  niveau_detail: "moyen"
  ton: "amical mais efficace"
